name: Go

on:
  push:
        branches:
          - master
          - feature/*
        paths-ignore:
          - '**/*.md'
          - .gitignore
          - .editorconfig
          - appveyor.yml
          - 'azure-pipelines*.yml'
          - 'ci/azure-pipelines/template*.yml'

        pull_request:
          branches:
            - master
            - feature/*
            - release/*
          paths-ignore:
            - '**/*.md'
            - .gitignore
            - .editorconfig
            - appveyor.yml
            - 'azure-pipelines*.yml'
            - 'ci/azure-pipelines/template*.yml'
jobs:

  Build test:
    runs-on: windows-latest
    strategy:
      matrix:
        ver: [ 'test','build' ]
        go: [ '1.15','1.14', '1.13','1.12','1.11',1.10','1,9' ]
    name: Go ${{ matrix.go }} ${{ matrix.ver }} 
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - name: Cache local go package
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - run: go ${{ matrix.ver }} 

